//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAchievement
    {
        public int AchievementId { get; set; }
        public int DoctorId { get; set; }
        public string Achievement { get; set; }
        public string AchievementDescription { get; set; }
        public Nullable<System.DateTime> AchievedDate { get; set; }
    }
}
