//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminIquiry
    {
        public int AdminInquiryID { get; set; }
        public string FirtsName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string ContactNo { get; set; }
        public string Subject { get; set; }
        public string Inquiry { get; set; }
        public System.DateTime InquiryOn { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyOn { get; set; }
        public Nullable<int> ReplyBy { get; set; }
        public bool IsReply { get; set; }
    }
}
