//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInHouseTreatement
    {
        public int InHouseTreatementId { get; set; }
        public int DoctorId { get; set; }
        public Nullable<int> AdmitDetailId { get; set; }
        public int PatientId { get; set; }
        public int NurseId { get; set; }
        public string MedicineName { get; set; }
        public string Treatement { get; set; }
        public string Remarks { get; set; }
        public System.TimeSpan TreatementTime { get; set; }
        public System.TimeSpan TreatedOn { get; set; }
        public bool IsGiven { get; set; }
    }
}
