//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewsLetter
    {
        public int NewsLetterId { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> SubscribedOn { get; set; }
        public Nullable<System.DateTime> UnSubscribedOn { get; set; }
        public bool IsSubscribed { get; set; }
    }
}
