//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrescriptionDetail
    {
        public int PrescriptionDetailsId { get; set; }
        public int PrescriptionId { get; set; }
        public string MedicineName { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Prescription { get; set; }
    }
}
