//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntenseCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int ReviewId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int Rating { get; set; }
        public System.DateTime ReviewedOn { get; set; }
    }
}
